var animal = "Honey Badger";
var isCuddly = false;
animal = "Mongoose";
console.log(animal);
var num8 = 8;
var num3 = 3;
var quotient = num3 / num8;
console.log(quotient);
var favoriteFilms = ['Judas and The Black Messiah', 'Get Out', 'Malcolm X'];
favoriteFilms.shift();
console.log(favoriteFilms);
console.log(animal.length);
